steps:
  - id: build-batch-jobs
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - -c
      - >-
        docker build
        --file=apps/batch-jobs/Dockerfile
        --tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
        --tag=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
        --cache-from=$_ARTIFACT_REPOSITORY_IMAGE_NAME:latest
        .
    dir: "."

  - id: push-batch-jobs
    name: "docker"
    args:
      - push
      - --all-tags
      - $_ARTIFACT_REPOSITORY_IMAGE_NAME
    waitFor: ["build-batch-jobs"]

  - id: deploy-batch-jobs
    name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - jobs
      - deploy
      - batch-jobs
      - --quiet
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
      - --service-account=$_SERVICE_ACCOUNT
      - --task-timeout=30m
      - --max-retries=3
      - --parallelism=1
      - --tasks=1
      - --cpu=1
      - --memory=512Mi
    waitFor: ["push-batch-jobs"]

timeout: 2000s

substitutions:
  _REGION: by-terraform
  _ARTIFACT_REPOSITORY_IMAGE_NAME: by-terraform
  _SERVICE_ACCOUNT: by-terraform

# ビルド結果に生成したイメージ情報を表示する
# https://cloud.google.com/build/docs/building/build-containers
images:
  - $_ARTIFACT_REPOSITORY_IMAGE_NAME:$SHORT_SHA
